### ISSUE TITLE
Translation work

### ISSUE THREAD

**Issue by h1z3y3** [cue-lang/cuelang.org#212]
@myitcv 
Have any plan on translation? I'd like to contribute.

**Comment by myitcv** [comment]
https://github.com/cue-lang/cue/issues/970 is the placeholder for this.

Providing translations of parts of the cuelang.org website is something that could start now, for example. Hugo and the [Docsy](https://www.docsy.dev/) theme we use have support for this. 

One request: if you do plan to investigate translating any parts of the CUE project, please coordinate via https://github.com/cue-lang/cue/issues/970 (I will close this issue in favour of that one).

Thanks very much for your offer of help!
