### ISSUE TITLE
website: redirect cuelang.org/cl like we do for cuelang.org/issue

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cuelang.org#264]
URLs like https://cuelang.org/issue/123 redirect to our issue tracker, currently https://github.com/cue-lang/cue/issues. It helps to use URLs like that because, if we ever need to move the issue tracker, the URLs can be redirected accordingly.

We should do the same for CLs; for example, https://cuelang.org/cl/538063 is just a 404, when it could redirect to https://review.gerrithub.io/c/cue-lang/cue/+/538063. As an extra bonus, note how much longer the real Gerrit URL is, so that will also help for commit messages.

**Comment by mvdan** [comment]
Transferred.

You're also right that the netlify config seems like the right place.

As for testing, note that Netlify deploys previews for each PR, so that is usually what we use for testing, e.g. https://github.com/cue-lang/cuelang.org/pull/250#issuecomment-1157797201

However, note that https://deploy-preview-250--cue.netlify.app/issue/123 doesn't work, beacuse the rewrite rule has `from = "https://cuelang.org/issue/*"`, hard-coding the production deploy URL. I wonder if we could make it work for previews as well, e.g. `from = "${DEPLOY_URL}/issue/*"` or somesuch. From looking at https://docs.netlify.com/routing/redirects/, I think that just `from = "/issue/*"` would work? cc @myitcv

**Comment by myitcv** [comment]
> From looking at https://docs.netlify.com/routing/redirects/, I think that just `from = "/issue/*"` would work? cc @myitcv

I don't know the answer TBH, but happy to try things out.

Also happy with the idea of a `/cl` direct - that would have been a better solution for the recent config change you approved, @mvdan .

**Comment by cedricgc** [comment]
I will try to get this out today/tomorrow. Since the change is fairly simple and shouldn't break anything existing, I figure we can eyeball the change and just try it rather than figure out some testing scheme for a minor change. I will adjust quickly if there is any issues

**Comment by myitcv** [comment]
Just noting that this redirect is more fragile than the GitHub based ones. Because we moved from a world where we "owned" the Gerrit instance (and hence had control over CL numbers) to a world where we share the Gerrit instance (and hence do not have control over CL numbers).

Hence, even CLs not connected to the CUE project resolve: https://cuelang.org/cl/541167.

And old CLs that relate to the previous Gerrit instance do not resolve to the old Gerrit instance: https://cuelang.org/cl/1680 (should redirect to https://cue-review.googlesource.com/c/cue/+/1680). So in the future we might want to make this redirect "smarter".

**Comment by mvdan** [comment]
Good point - I think this is okay for now. I seem to recall Go has a bit of logic in their redirect proxy to check if a CL number existed in either the old or new code review systems, to then issue the redirect.

**Comment by myitcv** [comment]
> I seem to recall Go has a bit of logic in their redirect proxy to check if a CL number existed in either the old or new code review systems, to then issue the redirect.

Exactly. But again, certainly not critical for now.
